# **Módulo 5: Python for Data Science (IBM)**

#### **Nombre:** Matthias Sibrian Illescas

#### **Matrícula:** a01794249

## **Módulo 5: Working with Numpy Arrays and Simple APIs**

### **Numpy 1D Arrays**


Numpy es una librería muy útil para computación científica en Python. Acá, un elemento muy importante es el ndarray, que es un arreglo con una longitud particular. Los elementos dentro son de un tipo definido también y se pueden accesar a través de su índice, similar al caso de las listas. Para castear una lista hacia un numpy array, esta es la sintaxis:

In [2]:

import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])


En numpy, se puede manipular los elementos de manera análoga al slicing y funciones básicas de las listas, como operaciones con índices y funciones universales, también como suma de vectores y de magnitudes. Realizar estas operaciones en numpy es muy conveniente porque sus métodos están optimizados para ello, lo cual lo hace mucho más rápido y eficiente que realizarlo a través de listas habituales.

Para realizar una multiplicación vectorial, la sintaxis es la siguiente:

In [3]:
y = np.array([1,2])
z=2*y
z

array([2, 4])

Otras funciones implementables en numpy son:
- media
- máximo
- mínimo
- seno, coseno, tangente
- linespace (usada para secuencias)

In [4]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [5]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

### **Lab - Working with 1D Numpy Arrays**

(Se realizó y se subió en la entrega de GitHub, en folder 'Labs')

### **Numpy 2D Arrays**

We can create Numpy arrays with more than one dimension.
This section will focus only on 2D arrays, but you can use Numpy to build arrays of much
higher dimensions.
In this video we will cover the basics and array creation in 2D, indexing and slicing
in 2D, and basic operations in 2D.

En numpy, existe la posibilidad de tener arreglos de dimensiones mayores a 1, a través de listas anidadas dentro de una matriz. A través del argumento 'ndim', se tiene acceso al número de dimensiones del objeto, el cual se conoce como 'rank'. 

Otra función importante es 'shape', la cual regresa una tupla al instanciarse. El primer elemento que retorna es la cantidad de listas anidadas contenidas. El segundo elemento corresponde al tamaño de cada una de las listas anidadas o el número de columnas. 

In [9]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
filas, cols = A.shape
filas

4

In [10]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B) #no son del mismo tamaño

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

### **Lab - Working with 2D Numpy Arrays**

(Se realizó y se subió en la entrega de GitHub, en folder 'Labs')

### **Simple APIs - Part 1**

Un API es una herramienta para comunicar dos instancias de software entre sí a través de entradas y salidas. Para usarla, no es necesario entender la manera en que está construida, sino solamente las entradas y salidas de la misma. 

Si una API se comunica a través del Internet, utiliza el protocolo HTTP para comunicarse, y será una API REST. La conveniencia de utilizar este tipo de API es que permite aprovechar la comunicación web para entrelazar aplicaciones entre sí. 

La comunicación que sigue al utilizar una API REST depende también de archivos JSON. Para especificar el recurso a consultar, se utiliza un archivo JSON con la consulta, y se recibe a su vez una respuesta en formato JSON. Este tipo de consultas sigue el modelo cliente-servidor, en donde la aplicación que consulta un recurso es el cliente del modelo.

### **Simple APIs - Part 2**

Un concepto clave de un API es el concepto de endpoint y el de keys. Básicamente, un endpoint es una ubicación a través de la cual se especifica la ubicación del servicio en la API. Por otro lado, para accesar un objeto de una API, se necesita las keys y los endpoints. De respuesta, se obtiene un diccionario, el cual contiene el resultado calculado para el objeto que se está consultando.

### **Lab - HTTP and Requests**

(Se realizó y se subió en la entrega de GitHub, en folder 'Labs')

### **Lab - API**

(Se realizó y se subió en la entrega de GitHub, en folder 'Labs')

### **Review Questions (4 Questions)**

In [12]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [13]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [14]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [16]:
A = np.random.randint(1,10,size = (3,3))
B = np.random.randint(1,10,size = (3,2))
np.dot(A,B)

array([[ 92,  98],
       [ 78,  68],
       [100, 133]])